"""Add Blogs table

Revision ID: 75844bac4c9d
Revises: ea894afabbc8
Create Date: 2019-06-10 15:18:19.034301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75844bac4c9d'
down_revision = 'ea894afabbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('postedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
