"""Add d column_id to coments table

Revision ID: b343bbfeaf9b
Revises: b47531fd71e9
Create Date: 2019-06-10 18:36:08.760915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b343bbfeaf9b'
down_revision = 'b47531fd71e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment_id')
    # ### end Alembic commands ###
