"""Adddd title column to Blogposts table

Revision ID: b47531fd71e9
Revises: c8d3cb84d4f8
Create Date: 2019-06-10 16:26:09.441904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47531fd71e9'
down_revision = 'c8d3cb84d4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
